// packages/ui-react/src/components/visualization-viewer/visualization-viewer.tsx
import { CSSProperties, useEffect, useMemo, useRef } from 'react';
import { VisualizationViewer as Viewer, VisualizationViewerOptions } from '@revealbi/ui';
import styles from './visualization-viewer.module.scss';

/* eslint-disable-next-line */
export interface VisualizationViewerProps {
  dashboard?: string | unknown;
  options?: VisualizationViewerOptions;
  style?: CSSProperties;
  visualization?: string | number;
}

export function VisualizationViewer(props: VisualizationViewerProps) {

  const { dashboard, options, style, visualization } = props;

  const defaultStyle: CSSProperties = { height: '100%', width: '100%', position: 'relative', minHeight: '250px' };
  const combinedStyle: CSSProperties = { ...defaultStyle, ...style }; // Merge with user-provided styles
  const uniqueId = useMemo(() => `revealView-${Math.random().toString(36).substr(2, 9)}`, []);  
  const dvRef = useRef<Viewer | null>(null);
  const revealViewReference = useRef(null);

  useEffect(() => {
    if (!dvRef.current && revealViewReference.current) {
      dvRef.current = new Viewer(revealViewReference.current, dashboard, visualization, options);
    }

    return () => {
      dvRef.current = null;
    }
  }, []);
  
  useEffect(() => {
    if (dvRef.current) {
      dvRef.current.updateOptions(options);
      dvRef.current.updateDashboard(dashboard, visualization);
    }
  }, [dashboard, options]);

  useEffect(() => {
    if (dvRef.current) {
      dvRef.current.updateVisualization(visualization);
    }
  }, [visualization]);

  return <div id={uniqueId} ref={revealViewReference} style={combinedStyle}></div>;
}

export default VisualizationViewer;

// packages/ui-angular/src/components/visualization-viewer/visualization-viewer.component.ts
import { CommonModule } from '@angular/common';
import { AfterViewInit, Component, ElementRef, Input, OnChanges, SimpleChanges, ViewChild } from '@angular/core';
import { VisualizationViewer, VisualizationViewerOptions } from '@revealbi/ui';

@Component({
  standalone: true,
  imports: [CommonModule],
  selector: 'visualization-viewer',
  template: `<div #revealView [id]="id"></div>`,
  styleUrls: ['./visualization-viewer.component.scss'],
})
export class VisualizationViewerComponent implements AfterViewInit, OnChanges {

  @ViewChild('revealView') el!: ElementRef;
  private viewer!: VisualizationViewer;
  id: string = `revealView-${Math.random().toString(36).substr(2, 9)}`; 

  /**
   * The dashboard to be displayed.
   */
  @Input() dashboard?: string | unknown;

  /**
   * The options to configure the visualization viewer.
   */
  @Input() options?: VisualizationViewerOptions;
  
  /**
   * The visualization to be displayed.
   */
  @Input() visualization?: string | number;

  ngAfterViewInit(): void {
    this.viewer = new VisualizationViewer(this.el.nativeElement, this.dashboard, this.visualization, this.options);
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes["dashboard"] && !changes["dashboard"].isFirstChange()) {
      this.viewer.updateDashboard(this.dashboard, this.visualization);
    } else if (changes["options"] && !changes["options"].isFirstChange()) {
      this.viewer.updateOptions(this.options);
    } else if (changes["visualization"] && !changes["visualization"].isFirstChange()) {
      this.viewer.updateVisualization(this.visualization);
    }
  }  
}
