// samples/sandbox-react/src/app/app.tsx
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { RevealSdkSettings, RevealViewOptions, SaveEventArgs } from '@revealbi/ui';
import { RevealView, RevealViewRef, RvDialog, RvDialogRef } from '@revealbi/ui-react';
import { useRef, useState } from 'react';
import styles from './app.module.scss';

export function App() {

  const rvRef = useRef<RevealViewRef>(null);
  const rvDialogRef = useRef<RvDialogRef>(null);;
  
  RevealSdkSettings.serverUrl = "https://samples.revealbi.io/upmedia-backend/reveal-api/";
  //RevealSdkSettings.serverUrl = "http://localhost:5111";

  const [dashboard, setDashboard] = useState<string>("Campaigns");

  const options: RevealViewOptions = {
    dataSources: [
      { type: "REST", title: "Sales by Category", subtitle: "Excel2Json", url: "https://excel2json.io/api/share/6e0f06b3-72d3-4fec-7984-08da43f56bb9" },
    ],
    header: {
      menu: {
        items: [
          { title: "Item 1", click: () => console.log(rvRef.current?.getRVDashboard())},
          { title: "Item 2", click: () => alert("Item 2") },
          { title: "Item 3", click: () => alert("Item 3") },
        ]
      }
    },
  }

  const footerButtonClick = () => {
    rvDialogRef.current?.close("save-button");    
    console.log("Save button clicked");
  }

  
  async function onSave(args: SaveEventArgs) {

    const result = await rvDialogRef.current?.show();

    if (result === "save-button") {
      args.dashboardId = args.name = result;
      args.saveFinished();
    } else {
      console.log("Save cancelled");
      return;
    }
  }

  return (
    <div style={{height: '100%'}}>
      <RevealView ref={rvRef} dashboard={dashboard} options={options} onSave={onSave} ></RevealView>

      <RvDialog ref={rvDialogRef} open={true} title="Save Dashboard">
        <h1>Do you want to save this dashboard?</h1>
        <div slot="footer">
          <button className="rv-button" onClick={footerButtonClick}>Save Button</button>
        </div>
      </RvDialog>
    </div>
  );
}

export default App;

// samples/sandbox-angular/src/app/app.component.ts
import { Component, ViewChild } from '@angular/core';
import { RouterModule } from '@angular/router';
import { RevealSdkSettings, RevealViewOptions, SaveEventArgs } from '@revealbi/ui';
import { DialogComponent, RevealViewComponent } from '@revealbi/ui-angular';

RevealSdkSettings.serverUrl = "https://samples.revealbi.io/upmedia-backend/reveal-api/";
//RevealSdkSettings.serverUrl = "http://localhost:5111";

@Component({
  standalone: true,
  imports: [RouterModule, DialogComponent, RevealViewComponent],
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss',
})
export class AppComponent {
  @ViewChild("revealView") revealView!: RevealViewComponent;
  @ViewChild("dialog") dialog!: DialogComponent;
  title = 'Save Dashboard';
  isOpen: boolean = true;

  visualization?: string | number = 2;
  dashboard?: string = "Campaigns";
  options: RevealViewOptions = {
    dataSources: [
      { type: "REST", title: "Sales by Category", subtitle: "Excel2Json", url: "https://excel2json.io/api/share/6e0f06b3-72d3-4fec-7984-08da43f56bb9" },
    ],
    header: {
      menu: {
        showMenu: true,
        items: [
          { title: "Item 1", click: (viz) => alert("Item 1") },
          { title: "Item 2", click: (viz) => alert("Item 2") },
          { title: "Item 3", click: (viz) => alert("Item 3") },
        ]
      }
    },
  }

  async ngOnInit() {

  }

  async onSave($event: SaveEventArgs) {

    const result = await this.dialog.show();

    if (result === "save-button") {
      $event.dashboardId = $event.name = result;
      $event.saveFinished();
    } else {
      console.log("Save cancelled");
      return;
    }

  }

  footerButtonClick() {
    const filter = this.revealView?.filters?.getByTitle("CampaignID");
    if (filter) {
        filter.selectedValues = ["Diamond", "Ruby"];
    }   
    this.dialog.close("save-button");
  }
}

<div style="height: 100%;">
    <reveal-view #revealView [dashboard]="dashboard" [options]="options" (save)="onSave($event)"></reveal-view>

    <!-- <visualization-viewer [dashboard]="dashboard" [visualization]="visualization"></visualization-viewer> -->
</div>

<ui-dialog #dialog [open]="isOpen" [title]="title">
    <!-- <div slot="icon">
            <img src="../favicon.ico">
        </div> -->

    <h1>Do you want to save this dashboard?</h1>

    <div slot="footer">
        <button class="rv-button" (click)="footerButtonClick()">Save Button</button>
    </div>
</ui-dialog>



<router-outlet></router-outlet>
